### ISSUE TITLE
汁について

### ISSUE THREAD

**Issue by hama6767** [hama6767/GikenFontPuremiamu#1]
# 汁

# 今語られる！！！！！！！汁の歴史！！！！！！！！！！！！！！

2018秋 ボンオドリサーバー　誕生
一ヶ月後　解散！！！
2018秋 汁　爆誕

以後右翼団体の活動拠点として活性化

2020春 共産主義政権、誕生！！！！！！
2020春 チマチョゴリ　大ブーム！！！！
2020秋 湯河原　全員負傷！！！！！
2021夏 紙部　発足！！！！！！！
2021秋 ラブプラス 大ブーム！！！！

語り継がれることになるだろう＿＿＿＿＿＿＿＿＿＿＿

**Comment by NaO0425** [comment]
This document the history of Shirushi. Edit together.[https://docs.google.com/document/d/1jkNstjiddFcOlq9yrhSZgTQD8Kw_1evIu8--op0l4Oc/edit?usp=sharing](url)
